name: Test (oracle)

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.8]

    steps:
    - uses: actions/checkout@v1
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Download Oracle Database setup script
      run: |
        mkdir oracle-scripts && cd oracle-scripts
        wget https://gist.github.com/laymonage/b40c032770adbae53b1b6029655f792f/raw/e7aed2dcfb16612b5488c252bfb4911ab5f8c2a0/01_create_user.sql
    - name: Run Oracle Database Docker image
      run: |
        docker pull quay.io/maksymbilenko/oracle-12c
        docker run --name oracle -d -p 1521:1521 -v `pwd`/oracle-scripts:/docker-entrypoint-initdb.d quay.io/maksymbilenko/oracle-12c
    - name: Install Oracle Instant Client
      run: |
        sudo apt update && sudo apt install alien
        wget https://download.oracle.com/otn_software/linux/instantclient/oracle-instantclient-basiclite-linuxx64.rpm
        sudo alien -i oracle-instantclient-basiclite-linuxx64.rpm
    - name: Wait for Oracle Database to finish setup
      run: |
        until docker logs oracle | grep "Database ready to use."; do echo "Waiting..." && sleep 5; done
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install tox tox-gh-actions
    - name: Test with tox
      run: tox
      env:
        DB_BACKEND: oracle
        DB_NAME: localhost/xe
        DB_USER: django
        DB_PASSWORD: django
